[package]
name = "i2c_dw_plat"
version = "0.1.0"
edition = "2021"
authors = ["Guoweikang <guoweikang.kernel@gmail.com>"]
description = "I2C common module"
license = "GPL-3.0-or-later OR Apache-2.0"
homepage = ""

[dependencies]
dw_apb_i2c = {path="../../dw-apb-i2c"}
